#!/usr/bin/perl

# Copyright (c) 2016 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;

use VOIP::MS;
my ($user,$pass);
my $conffile=$ENV{'HOME'}."/.voipms.conf";
my $config = { };
if (-f $conffile) {
	if (!open(CF,"$conffile")) {
		print "open of $conffile failed, aborting\n";
		exit(1);
	}
	my $line;
	while(<CF>) {
		chomp($line = $_);
		if ($line =~ /^([a-z0-9]+)\s*=\s*(.*)$/) {
			my ($var, $val) = ($1,$2);
			$config->{$var} = $val;
			#printf "config: '%s' = '%s'\n",$var,$val;
		}
	}
}
if (!defined($config->{user}) || !defined($config->{pass})) {
	print "User or Pass is Null and void, bailing for now\n";
	exit(1);
}
my $voip = VOIP::MS->new(username => $config->{user},
	password => $config->{pass});
my $balinfo= $voip->getBalance();
use Data::Dumper;
my $d = Data::Dumper->new([$balinfo]);
print $d->Dump();

# the following 'if (0)' bits work, they're just verbose; enable if desired
# this is a wip anyway, will get re-done once enough apis are implemented
if (0) {
my $cdr = $voip->getCDR( { date_from => '2016-08-01', date_to => '2016-09-01'} );
$d = Data::Dumper->new([$cdr]);
print $d->Dump();
}

if (0) {
my $slist = $voip->getServersInfo(); # optional: server_pop => 1
$d = Data::Dumper->new([$slist]);
print $d->Dump();
}

if (0) {
my $ret = $voip->getCallAccounts(); # optional: client => 56115
my $i=0;
foreach my $acct (@$ret) {
	if ($acct->{value} eq $acct->{description}) {
		$acct->{description} = "";
	}
	printf "%2d. %12s %s\n", $i++, $acct->{value}, $acct->{description};
	if ($acct->{value} eq "all") {
		next;
	}
	my $r = $voip->getRegistrationStatus(account => $acct->{value});
	$d = Data::Dumper->new([$r]);
	print $d->Dump();
}
}
	
if (0) {
my $ret = $voip->getCallBilling();
$d = Data::Dumper->new([$ret]);
print $d->Dump();
}
if (0) {
my $ret = $voip->getCallTypes(); # optional: client => 56115
$d = Data::Dumper->new([$ret]);
print $d->Dump();
}
if (0) {
my $ret = $voip->getRegistrationStatus(account => $config->{account0});
$d = Data::Dumper->new([$ret]);
print $d->Dump();
}
if (0) {
my $cdr = $voip->getSMS( { from => '2016-08-01', to => '2016-09-01'} );
$d = Data::Dumper->new([$cdr]);
print $d->Dump();
}
if (0) { # hmmm, what is a callback exactly?
my $cb = { };
$cb->{description} = 'testing 1 2 3';
$cb->{number} = '14057791633';
$cb->{delay_before} = '30';
$cb->{response_timeout} = '30';
$cb->{digit_timeout} = '5';
# optional
$cb->{callerid_number} = '14058267307';
my $cdr = $voip->setCallback( $cb );
$d = Data::Dumper->new([$cdr]);
print $d->Dump();
}
if (0) { # how to create a package?
my $ret = $voip->getPackages(); # optional: package => 8378
$d = Data::Dumper->new([$ret]);
print $d->Dump();
}

if (1) {
# optional: client => '' || '5615' || '5615_VoIP'
# optional: did => 1231231234
my $ret = $voip->getDIDsInfo();
$d = Data::Dumper->new([$ret]);
print $d->Dump();
}
